const TOKTRACK_PACKAGE_NAME = 'toktrack'
const TOKTRACK_VERSION = '2.4.0'
const TOKTRACK_PACKAGE_SPEC = `${TOKTRACK_PACKAGE_NAME}@${TOKTRACK_VERSION}`

module.exports = {
  TOKTRACK_PACKAGE_NAME,
  TOKTRACK_VERSION,
  TOKTRACK_PACKAGE_SPEC,
}
